name: bf_app
description: "BF (뷰파) - Beauty AI Agent Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 기본 패키지
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.4.4
  dio: ^5.3.3 # HTTP 클라이언트 라이브러리
  
  # 인증 및 백엔드
  supabase_flutter: ^2.3.0
  google_sign_in: ^6.1.5
  
  # 모델 클래스 어노테이션
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # UI/UX
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  
  # 이미지 처리
  image_picker: ^1.0.4
  camera: ^0.10.5
  
  # 상태 관리
  provider: ^6.1.1
  
  # 네비게이션
  go_router: ^13.0.0
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  
  # 유틸리티
  intl: ^0.18.1
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  
  # 차트/그래프
  fl_chart: ^0.66.0
  
  # 권한 관리
  permission_handler: ^11.1.0

  # confetti
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ⭐ 코드 생성을 위한 필수 개발 도구들 추가
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  # 에셋 설정
  assets:
    - assets/1-1/
    - assets/1-2/
    - assets/1-3/
    - assets/2-1/
    - assets/2-2/
    - assets/2-3/
    - assets/3/
    - assets/4/
    - assets/5and11/
    - assets/6/
    - assets/7/
    - assets/8/
    - assets/9/
    - assets/10/
    - assets/12/
    - assets/13/
    - assets/15-1,2/
    - assets/16/
    - assets/17/personalcolor/
    - assets/17/skin/
    - assets/17/
  
  # 폰트 설정
  fonts:
    # Crimson Text 폰트
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText/CrimsonText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CrimsonText/CrimsonText-Regular.ttf
        - asset: assets/fonts/CrimsonText/CrimsonText-Bold.ttf
          weight: 700
        - asset: assets/fonts/CrimsonText/CrimsonText-BoldItalic.ttf
          weight: 700
          style: italic
    
    # SF Pro Display 폰트
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
          weight: 900